avatar:
  enable: true
  url: /img/avatar.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜„
    message: Happy


banner:
  enable: true
  title: å’–å•¡ä¸èŒ¶çš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line


reward:
  enable: false